# Generated by Django 5.1.1 on 2024-11-26 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'managed': False, 'verbose_name': 'Логи', 'verbose_name_plural': 'Логи'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'managed': False, 'verbose_name': 'Товары', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='producttypes',
            options={'managed': False, 'verbose_name': 'Типы продуктов', 'verbose_name_plural': 'Типы продуктов'},
        ),
        migrations.AlterModelOptions(
            name='requests',
            options={'managed': False, 'verbose_name': 'Запросы', 'verbose_name_plural': 'Запросы'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'managed': False, 'verbose_name': 'Роли', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterModelOptions(
            name='smartcontracts',
            options={'managed': False, 'verbose_name': 'Смарт контракты', 'verbose_name_plural': 'Смарт контракты'},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'managed': False, 'verbose_name': 'Транзакции', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AlterModelOptions(
            name='userlogs',
            options={'managed': False, 'verbose_name': 'Логи Пользователей', 'verbose_name_plural': 'Логи Пользователей'},
        ),
        migrations.AlterModelOptions(
            name='userrequests',
            options={'managed': False, 'verbose_name': 'Запросы пользователей', 'verbose_name_plural': 'Запросы пользователей'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False, 'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='usertransactions',
            options={'managed': False, 'verbose_name': 'Транзакции пользователей', 'verbose_name_plural': 'Транзакции пользователей'},
        ),
    ]
