# Generated by Django 5.1.1 on 2024-12-01 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0002_alter_logs_options_alter_products_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'managed': True, 'verbose_name': 'Логи', 'verbose_name_plural': 'Логи'},
        ),
    ]
