# Generated by Django 5.1.1 on 2024-12-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0003_alter_logs_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='is_auto_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='logs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
