# Generated by Django 5.1.1 on 2024-12-03 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0004_logs_is_auto_created_alter_logs_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='is_auto_created',
        ),
    ]
