# Generated by Django 5.1.1 on 2024-12-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0006_logs_is_auto_created_alter_logs_interaction_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True, 'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
